### ISSUE TITLE
Using the field

### ISSUE THREAD

**Issue by Beatusvir** [saadahmedkhan/sitecore-fields#6]
Hey guys, I was hesitant to post this question cos it seems a little stupid, but how in gods name do I use this field on the page? I'm sure its me not understanding but if I want one of the thumbnails on my page, how do I get, lets say a 150x300? My templates has among other fields, a field Image which is the advance image, how should my razor look like?

**Comment by dnstommy** [comment]
You would use it like this. Where fieldName is the name if the field on the item and item is the item that you are using as a datasource. It was added in this commit. https://github.com/saadahmedkhan/sitecore-fields/commit/008e555c604dbc4e83c71783becccaafe69cec66

@Html.Sitecore().AdvancedImageField("fieldName", item, 150, 300)

**Comment by Beatusvir** [comment]
Forgot to mention the error I was getting was because I didnt have ImageProcessor dependency, so sitecore was not resizing / cropping images.
